ALTER TABLE orders ADD COLUMN discount_code TEXT;
ALTER TABLE orders ADD COLUMN discount_amount REAL NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN subtotal_items REAL NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN shipping_amount REAL NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN tax_amount REAL NOT NULL DEFAULT 0;
